### ISSUE TITLE
Api-Not working

### ISSUE THREAD

**Issue by Whitehat267** [anime-kun32/AniTeams#5]
Api i not working. It maybe that the api is taken down. Please re-host the previous api or update the code to this api:
[Anime-New-Api](https://ani-api-rosy.vercel.app/)

**Comment by anime-kun32** [comment]
The website is now available it's up and running but please note that on Wednesday there will be a new branch added because I have  have a completely new layout

**Comment by Whitehat267** [comment]
Thank you!!

**Comment by Whitehat267** [comment]
Thank you
