### ISSUE TITLE
remove your firebase auth data from the signup page

### ISSUE THREAD

**Issue by apurvsikka** [anime-kun32/AniTeams#7]

**Comment by anime-kun32** [comment]
Oh sorry I forgot to remove that I was just testing it out , so I plan to fully integrate login and sign up to the site

**Comment by apurvsikka** [comment]
also , try to make an anilist auth workflow instead of firebase sso , it is way better for anime-related stuff check it out at [https://docs.anilist.co/guide/auth/](url)

**Comment by anime-kun32** [comment]
Alright thanks I will include in my checklist

**Comment by anime-kun32** [comment]
Any other issues?

**Comment by apurvsikka** [comment]
make a basic http server to serve your files instead of straight-up shoving html files in the web site

**Comment by anime-kun32** [comment]
Ok then
